# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bootstrap the Mean of a Numeric Vector
#'
#' Draws `reps` bootstrap resamples (sampling with replacement) of `x` and
#' returns the mean of each resample. This is the compute kernel that the
#' package distributes across _mirai_ daemons.
#'
#' @param x    A `numeric` vector to resample.
#' @param reps The number of bootstrap resamples to draw.
#'
#' @return
#' A `numeric` vector of length `reps` holding the bootstrap distribution of
#' the mean.
#'
#' @details
#' The routine uses _R_'s random number generator through `R::unif_rand()`.
#' When the kernel runs on a _mirai_ daemon, each daemon is given its own
#' independent random number stream, so resamples drawn in parallel remain
#' statistically sound.
#'
#' @examples
#' bootstrap_mean(rnorm(100), reps = 10)
#'
#' @export
bootstrap_mean <- function(x, reps) {
    .Call(`_RcppMirai_bootstrap_mean`, x, reps)
}

